### ISSUE TITLE
Couldn't pass PacketReceiveEvent to unsignedvelocity

### ISSUE THREAD

**Issue by SrBedrock** [4drian3d/UnSignedVelocity#14]
Error:
```
[14:40:03] [Velocity Async Event Executor - #12/ERROR] [com.velocitypowered.proxy.event.VelocityEventManager]: Couldn't pass PacketReceiveEvent to unsignedvelocity
java.lang.ClassCastException: class com.velocitypowered.proxy.protocol.packet.chat.keyed.KeyedPlayerChat cannot be cast to class com.velocitypowered.proxy.protocol.packet.chat.session.SessionPlayerChat (com.velocitypowered.proxy.protocol.packet.chat.keyed.KeyedPlayerChat and com.velocitypowered.proxy.protocol.packet.chat.session.SessionPlayerChat are in unnamed module of loader 'app')
	at io.github._4drian3d.unsignedvelocity.listener.packet.chat.SessionChatListener.onChat(SessionChatListener.java:42) ~[?:?]
	at com.velocitypowered.api.event.EventHandler.executeAsync(EventHandler.java:23) ~[server.jar:3.2.0-SNAPSHOT (git-9149ed33-b230)]
	at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[server.jar:3.2.0-SNAPSHOT (git-9149ed33-b230)]
	at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[server.jar:3.2.0-SNAPSHOT (git-9149ed33-b230)]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

Velocity version: `3.2.0-SNAPSHOT (git-9149ed33-b230)`
UnSignedVelocity version: `1.3.0`
VPacketEvents version: `1.0.1`

**Comment by 4drian3d** [comment]
The link you sent has no content

**Comment by SrBedrock** [comment]
> Reference

sorry, issue updated.

**Comment by 4drian3d** [comment]
Fixed at https://github.com/4drian3d/UnSignedVelocity/releases/tag/1.3.1 thank you for reporting
